
apiVersion: v1
kind: Service
metadata:
  name: ms-lanchonete-product-service
spec:
  selector:
    app: ms-lanchonete-product-deployment
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000
  type: LoadBalancer

