
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-lanchonete-product-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-lanchonete-product-deployment
  template:
    metadata:
      labels:
        app: ms-lanchonete-product-deployment
    spec:
      containers:
      - name: ms-lanchonete-product
        image: rmontoza/mslanchoneteproduct:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: ms-lanchonete-product-config
              key: MONGODB_URI
        volumeMounts:
        - name: ms-lanchonete-product-volume
          mountPath: /app
        ##command: ["/start-web.sh"]  # Substitua isso pelo comando de início apropriado, se necessário
      volumes:
      - name: ms-lanchonete-product-volume
        emptyDir: {}
